image: golang:1.15



stages:
  - build
  - test



# do not forget to set project variables
include:
  - template: SAST.gitlab-ci.yml # GITLAB_FEATURES = "sast"
  #- template: Code-Quality.gitlab-ci.yml # GITLAB_FEATURES = "code_quality"
  #- template: Dependency-Scanning.gitlab-ci.yml # GITLAB_FEATURES = "dependency_scanning"
  #- template: License-Scanning.gitlab-ci.yml # GITLAB_FEATURES = "license_scanning"

variables:
  SAST_DISABLE_DIND: "true"
  SAST_GOSEC_LEVEL: 0



.build_command: &build_command
- go build ./...

.test_command: &test_command
- go test ./... -cover



build-master:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
  script:
    - *build_command

test-master:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
  script:
    - *test_command



build-not-master:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: always
      allow_failure: true
  script:
    - *build_command

test-not-master:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: on_success
      allow_failure: true
  script:
    - *test_command
